name: traefik
apiVersion: v2
version: 1.0.0
dependencies:
  - name: traefik
    version: 31.1.1
    repository: https://helm.traefik.io/traefik
  - name: cluster-common
    version: "0.1.0"
    repository: "https://omer-bar.github.io/Homelab/charts/"
